-- 코드를 입력하세요
# SELECT COUNT(*)
# FROM (
#     SELECT NAME
#     FROM ANIMAL_INS
#     GROUP BY NAME
#     HAVING NAME IS NOT NULL
# ) AS 아무이름

WITH A AS (SELECT NAME FROM ANIMAL_INS GROUP BY NAME HAVING NAME IS NOT NULL)

SELECT COUNT(*) FROM A