WITH TEMP AS (SELECT DISTINCT A.ITEM_ID
              FROM ITEM_TREE A JOIN ITEM_TREE B
              ON A.ITEM_ID = B.PARENT_ITEM_ID)

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO 
WHERE ITEM_ID NOT IN (SELECT * FROM TEMP)
ORDER BY ITEM_ID DESC