WITH AVAILABLE_CAR AS (SELECT DISTINCT A.CAR_ID, CAR_TYPE, DAILY_FEE
                       FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
                       ON A.CAR_ID = B.CAR_ID AND CAR_TYPE IN ('세단', 'SUV')
                       WHERE A.CAR_ID NOT IN (SELECT CAR_ID
                                              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                                              WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01')),
     DISCOUNT_PLAN AS (SELECT CAR_TYPE, (1-DISCOUNT_RATE/100) DISCOUNT
                  FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                  WHERE CAR_TYPE IN ('세단', 'SUV') AND DURATION_TYPE LIKE '30%')

SELECT CAR_ID, A.CAR_TYPE, ROUND(30*DAILY_FEE*DISCOUNT) FEE
FROM AVAILABLE_CAR A JOIN DISCOUNT_PLAN B
ON A.CAR_TYPE = B.CAR_TYPE
WHERE 30*DAILY_FEE*DISCOUNT BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, A.CAR_TYPE, CAR_ID DESC