WITH B AS (SELECT FOOD_TYPE, MAX(FAVORITES) MAX_FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE)

SELECT A.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO A JOIN B
ON A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES = B.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC