SELECT ID, (CASE
            WHEN RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) / (SELECT COUNT(SIZE_OF_COLONY) FROM ECOLI_DATA) > 0.75 THEN 'LOW'
            WHEN RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) / (SELECT COUNT(SIZE_OF_COLONY) FROM ECOLI_DATA) > 0.5 THEN 'MEDIUM'
            WHEN RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) / (SELECT COUNT(SIZE_OF_COLONY) FROM ECOLI_DATA) > 0.25 THEN 'HIGH'
            ELSE 'CRITICAL'
            END) AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID