SELECT R.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) SCORE
FROM REST_INFO I JOIN REST_REVIEW R
ON I.REST_ID = R.REST_ID AND ADDRESS LIKE '서울%'
GROUP BY R.REST_ID
ORDER BY 6 DESC, 4 DESC