SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH,
COUNT(DISTINCT A.USER_ID) PUCHASED_USER,
ROUND(COUNT(DISTINCT A.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) PUCHASED_RATIO
FROM USER_INFO A JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID AND YEAR(JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH