WITH CTE AS (SELECT HISTORY_ID, DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
WHERE C.DURATION_TYPE = (CASE
                         WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN '90일 이상'
                         WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '30일 이상'
                         WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN '7일 이상'
                         END))
                         
SELECT B.HISTORY_ID,
       ROUND(DAILY_FEE * (1-IFNULL(DISCOUNT_RATE, 0)/100) * (DATEDIFF(END_DATE, START_DATE)+1)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID AND A.CAR_TYPE = '트럭'
LEFT JOIN CTE C ON B.HISTORY_ID = C.HISTORY_ID
ORDER BY 2 DESC, 1 DESC 