WITH RECURSIVE TIME AS (SELECT 0 AS HOUR
                        UNION ALL
                        SELECT HOUR+1 FROM TIME WHERE HOUR < 23)

SELECT B.HOUR, IFNULL(COUNT(A.ANIMAL_ID), 0) COUNT
FROM ANIMAL_OUTS A RIGHT JOIN TIME B
ON HOUR(A.DATETIME) = B.HOUR
GROUP BY HOUR
ORDER BY HOUR