WITH CTE AS (SELECT B.ITEM_ID FROM ITEM_INFO A JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID WHERE A.RARITY = 'RARE')

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO A JOIN CTE B
USING (ITEM_ID)
ORDER BY ITEM_ID DESC